name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Pastikan TOKEN_ULAR ini ada di Settings > Secrets
          token: ${{ secrets.TOKEN_ULAR }} 

          # Setting User
          user: diulll
          template: classic
          config_timezone: Asia/Jakarta
          filename: github-metrics.svg
          
          # Isi Gambar (Lengkap)
          base: header, activity, community, repositories, metadata
          plugin_streak: yes
          plugin_languages: yes
          plugin_lines: yes
